apiVersion: v1
values:
  images:
    job: cloudogu/k8s-ces-assets:0.0.1
patches:
  values.yaml:
    job:
      image:
        registry: "{{ registryFrom .images.job }}"
        repository: "{{ repositoryFrom .images.job }}"
        tag: "{{ tagFrom .images.job }}"
