apiVersion: v1
values:
  images:
    manager: cloudogu/k8s-ces-assets:0.1.0
    warp: cloudogu/k8s-ces-assets:0.1.0
    maintenance: cloudogu/k8s-ces-assets:0.1.0
patches:
  values.yaml:
    nginx:
      manager:
        image:
          registry: "{{ registryFrom .images.manager }}"
          repository: "{{ repositoryFrom .images.manager }}"
          tag: "{{ tagFrom .images.manager }}"
      warp:
        image:
          registry: "{{ registryFrom .images.warp }}"
          repository: "{{ repositoryFrom .images.warp }}"
          tag: "{{ tagFrom .images.warp }}"
      maintenance:
        image:
          registry: "{{ registryFrom .images.maintenance }}"
          repository: "{{ repositoryFrom .images.maintenance }}"
          tag: "{{ tagFrom .images.maintenance }}"
