apiVersion: v1
values:
  images:
    manager: docker.io/cloudogu/k8s-ces-assets:1.0.4
    warp: docker.io/cloudogu/k8s-ces-assets-warp:1.0.4
    maintenance: docker.io/cloudogu/k8s-ces-assets-maintenance:1.0.4
patches:
  values.yaml:
    nginx:
      manager:
        image:
          registry: "{{ registryFrom .images.manager }}"
          repository: "{{ repositoryFrom .images.manager }}"
          tag: "{{ tagFrom .images.manager }}"
      warp:
        image:
          registry: "{{ registryFrom .images.warp }}"
          repository: "{{ repositoryFrom .images.warp }}"
          tag: "{{ tagFrom .images.warp }}"
      maintenance:
        image:
          registry: "{{ registryFrom .images.maintenance }}"
          repository: "{{ repositoryFrom .images.maintenance }}"
          tag: "{{ tagFrom .images.maintenance }}"
