global:
  imagePullSecrets:
    - name: "ces-container-registries"
service:
  port: 80
  targetPort: 80
ingress:
  className: "k8s-ecosystem-ces-service"
  host: ""
  path: "/"
  pathType: "Prefix"
  annotations: {}
controllerManager:
  manager:
    env:
      stage: production
      logLevel: info
    image:
      registry: docker.io
      repository: cloudogu/k8s-ces-assets
      tag: 0.0.2
    imagePullPolicy: Always
    config:
      defaultDogu: "usrmgmt"
      disableAccessLog: false
      htmlContentUrl: "static"
    resources:
      requests:
        cpu: 15m
        memory: 105M
      limits:
        memory: 105M
