{{- $root := . -}}
{{- $base := "resources" -}}
{{- $files := $root.Files.Glob (printf "%s/**" $base) -}}
{{- if or (not $files) (eq (len $files) 0) -}}
{{- fail (printf "Keine Dateien unter %q gefunden – Pfad oder .helmignore prüfen." $base) -}}
{{- end -}}

{{- /* Volume-ConfigMap items vorbereiten: [{key:<filename>, path:<rel>}, ...] */ -}}
{{- $cmItems := list -}}
{{- $mountItems := list -}}
{{- range $path, $_ := $files }}
  {{- $rel  := trimPrefix (printf "%s/" $base) $path -}}
  {{- $name := base $rel -}}
  {{- $cmItems = append $cmItems (dict
          "key" $name
          "path" $rel) -}}
  {{- $mountItems  = append $mountItems (dict
          "name"      "app-config"
          "mountPath" (printf "%s" $rel)
          "subPath"   $rel
          "readOnly"  true ) -}}
{{- end -}}

{{- /* Volume-Mount for all custom-html config-maps*/ -}}
{{- $mountItems = append $mountItems (dict
        "name"      "customhtml-dst"
        "mountPath" .Values.initContainer.customHtmlMountPath
        "readOnly"  true ) -}}

{{- /* Volume--Mount for sharing warp-json between manager and warp-sidecard */ -}}
{{- $mountItems = append $mountItems (dict
        "name"      "warp-json"
        "mountPath" .Values.nginx.warp.mountPath) -}}

{{- /* Volume--Mount for sharing error-pages between manager and maintenance-sidecard */ -}}
{{- $mountItems = append $mountItems (dict
        "name"      "error-503"
        "mountPath" "/var/www/html/errors") -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-ces-assets.name" . }}-nginx
  labels:
  {{- include "k8s-ces-assets.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
    {{- include "k8s-ces-assets.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "k8s-ces-assets.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
        - name: customhtml-src
          configMap:
            name: "{{ .Values.initContainer.configMapName }}"
        - name: customhtml-dst
          emptyDir: {}
        - name: app-config
          configMap:
            name:  k8s-ces-assets-nginx-conf
            items:
              {{- toYaml $cmItems | nindent 14 }}
        - name: warp-json
          emptyDir: {}
        - name: error-503
          emptyDir: {}
      initContainers:
        - name: copy-customhtml
          image: "{{ .Values.nginx.manager.image.registry }}/{{ .Values.nginx.manager.image.repository }}:{{ .Values.nginx.manager.image.tag }}"
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              set -eu;
              SRC=/config;
              DST=/workdir;
              mkdir -p "$DST";
              if [ "$(ls -A "$SRC" 2>/dev/null || true)" ]; then
                cp -a "$SRC/." "$DST/";
              fi;
              SRC="/var/www/html/errors";
              DST="/tmp/errors";
              mkdir -p "$DST";
              if [ -d "$SRC" ]; then
                cp -r "$SRC/." "$DST/";
              fi;
          volumeMounts:
            - name: customhtml-src
              mountPath: /config
            - name: customhtml-dst
              mountPath: /workdir
            - name: error-503
              mountPath: /tmp/errors
      containers:
      - name: manager
        env:
        - name: STAGE
          value: {{ quote .Values.nginx.manager.env.stage | default "production" }}
        - name: LOG_LEVEL
          value: {{ quote .Values.nginx.manager.env.logLevel | default "info"}}
        image: "{{ .Values.nginx.manager.image.registry }}/{{ .Values.nginx.manager.image.repository }}:{{ .Values.nginx.manager.image.tag }}"
        imagePullPolicy: {{ .Values.nginx.manager.imagePullPolicy }}
        volumeMounts:
          {{- toYaml $mountItems | nindent 12 }}
        securityContext:
          allowPrivilegeEscalation: false
      - name: warp
        image: "{{ .Values.nginx.warp.image.registry }}/{{ .Values.nginx.warp.image.repository }}:{{ .Values.nginx.warp.image.tag }}"
        imagePullPolicy: {{ .Values.nginx.warp.imagePullPolicy }}
        volumeMounts:
        - name: "warp-json"
          mountPath: {{ quote .Values.nginx.warp.mountPath }}
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: WARP_PATH
          value: {{ quote .Values.nginx.warp.mountPath | default "/var/www/html/warp/"}}
        - name: LOG_LEVEL
          value: {{ quote .Values.nginx.warp.env.logLevel | default "info"}}
      - name: maintenance
        image: "{{ .Values.nginx.maintenance.image.registry }}/{{ .Values.nginx.maintenance.image.repository }}:{{ .Values.nginx.maintenance.image.tag }}"
        imagePullPolicy: {{ .Values.nginx.maintenance.imagePullPolicy }}
        volumeMounts:
        - name: "error-503"
          mountPath: "/var/www/html/errors"
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: LOG_LEVEL
          value: {{ quote .Values.nginx.warp.env.logLevel | default "info"}}
      securityContext:
        runAsNonRoot: false
      serviceAccountName: {{ include "k8s-ces-assets.name" . }}-nginx
      terminationGracePeriodSeconds: 10