apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-ces-assets.name" . }}-controller-manager
  labels:
  {{- include "k8s-ces-assets.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
    {{- include "k8s-ces-assets.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "k8s-ces-assets.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
        - name: app-config
          configMap:
            name:  k8s-ces-assets-nginx-conf
            items:
            {{- range $i, $cm := .Values.controllerManager.manager.configMaps | default (list) }}
              - key: {{ $cm.name | quote }}
                path: {{ $cm.path | quote }}
            {{- end }}
      containers:
      - args:
          - --health-probe-bind-address=:8081
          - --metrics-bind-address=127.0.0.1:8080
        name: manager
        env:
        - name: STAGE
          value: {{ quote .Values.controllerManager.manager.env.stage | default "production" }}
        - name: LOG_LEVEL
          value: {{ quote .Values.controllerManager.manager.env.logLevel | default "info"}}
        image: "{{ .Values.controllerManager.manager.image.registry }}/{{ .Values.controllerManager.manager.image.repository }}:{{ .Values.controllerManager.manager.image.tag }}"
        imagePullPolicy: {{ .Values.controllerManager.manager.imagePullPolicy }}
        volumeMounts:
          {{- range .Values.controllerManager.manager.configMaps }}
          - name: app-config
            mountPath: /etc/nginx/{{ .path }}
            subPath: {{ .path }}
            readOnly: true
          {{- end }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
      securityContext:
        runAsNonRoot: false
      terminationGracePeriodSeconds: 10