{{- $root := . -}}
{{- $base := "resources/etc/nginx" -}}
{{- $files := $root.Files.Glob (printf "%s/**" $base) -}}
{{- if or (not $files) (eq (len $files) 0) -}}
{{- fail (printf "Keine Dateien unter %q gefunden – Pfad oder .helmignore prüfen." $base) -}}
{{- end -}}

{{- /* Volume-ConfigMap items vorbereiten: [{key:<filename>, path:<rel>}, ...] */ -}}
{{- $cmItems := list -}}
{{- $mountItems := list -}}
{{- range $path, $_ := $files }}
  {{- $rel  := trimPrefix (printf "%s/" $base) $path -}}
  {{- $name := base $rel -}}
  {{- $cmItems = append $cmItems (dict
          "key" $name
          "path" $rel) -}}
  {{- $mountItems  = append $mountItems (dict
          "name"      "app-config"
          "mountPath" (printf "/etc/nginx/%s" $rel)
          "subPath"   $rel
          "readOnly"  true ) -}}
{{- end -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-ces-assets.name" . }}-controller-manager
  labels:
  {{- include "k8s-ces-assets.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
    {{- include "k8s-ces-assets.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "k8s-ces-assets.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
        - name: app-config
          configMap:
            name:  k8s-ces-assets-nginx-conf
            items:
              {{- toYaml $cmItems | nindent 14 }}
      containers:
      - name: manager
        env:
        - name: STAGE
          value: {{ quote .Values.controllerManager.manager.env.stage | default "production" }}
        - name: LOG_LEVEL
          value: {{ quote .Values.controllerManager.manager.env.logLevel | default "info"}}
        image: "{{ .Values.controllerManager.manager.image.registry }}/{{ .Values.controllerManager.manager.image.repository }}:{{ .Values.controllerManager.manager.image.tag }}"
        imagePullPolicy: {{ .Values.controllerManager.manager.imagePullPolicy }}
        volumeMounts:
          {{- toYaml $mountItems | nindent 12 }}
        securityContext:
          allowPrivilegeEscalation: false
      securityContext:
        runAsNonRoot: false
      terminationGracePeriodSeconds: 10