apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "k8s-ces-assets.name" . }}-warp-menu-role-binding
  namespace: '{{ .Release.Namespace }}'
  labels:
  {{- include "k8s-ces-assets.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "k8s-ces-assets.name" . }}-warp-menu-role'
subjects:
  - kind: ServiceAccount
    name: '{{ include "k8s-ces-assets.name" . }}-nginx'