apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-ces-assets.name" . }}-service
spec:
  type: ClusterIP
  selector:
{{- include "k8s-ces-assets.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP